services: 
  caddy: 
    image: caddy:latest
    container_name: "caddy-server"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chat_app

  frontend:
    image: oven/bun:alpine
    container_name: "chat-app-frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/www/app:rw
    working_dir: /www/app
    command: ["bun", "dev"] # Development
    networks:
      - chat_app


volumes: 
  caddy_data:
  caddy_config:

networks:
  chat_app:
    driver: bridge